spring:
  #Configuracion del data source
  datasource:
    url: jdbc:mysql://localhost:3306/resenas_peliculas?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  #configuracion de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Configuracion de Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false

  #Configurar DevTools
  devtools:
    restart:
      enabled: true
  application:
    version: 1.0.0

#Configurar el servidor embebido (Tomcat)
server:
  port: 8080

app:
  name: Proyecto Reseñas Backend
  version: ${APP_VERSION:dev} # Leído desde variables de entorno
  build-number: ${BUILD_NUMBER:0} # Leído desde variables de entorno
  commit-hash: ${COMMIT_HASH:unknown} # Leído desde variables de entorno

jwt:
  secret-key: "ESTA-ES-UNA-CLAVE-SECRETA-MUY-LARGA-Y-COMPLEJA-PARA-PRODUCCION-CAMBIAME"
